# Neurite Production Docker Compose Configuration
# Optimized for production deployment

version: '3.8'

services:
  # Frontend Service (Production)
  neurite-frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      - neurite-data:/app/data
    depends_on:
      - neurite-backend
    networks:
      - neurite-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend Service (Production)
  neurite-backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "7070:7070"
    environment:
      - NODE_ENV=production
      - PORT=7070
    volumes:
      - neurite-data:/app/data
      - neurite-logs:/app/logs
    networks:
      - neurite-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7070/check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx Reverse Proxy (Production)
  neurite-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - neurite-ssl:/etc/nginx/ssl
      - neurite-logs:/var/log/nginx
    depends_on:
      - neurite-frontend
      - neurite-backend
    networks:
      - neurite-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Redis Cache (Optional)
  neurite-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - neurite-redis:/data
    networks:
      - neurite-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    profiles:
      - cache

volumes:
  neurite-data:
    driver: local
  neurite-logs:
    driver: local
  neurite-ssl:
    driver: local
  neurite-redis:
    driver: local

networks:
  neurite-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
